services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile 
    container_name: apache-web
    volumes:
      - ../src:/var/www/html
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8080:80"
    depends_on:
      - db 
    environment:
      MYSQL_HOST: db 
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: web_dev_db
    restart: always

  db:
    image: mysql:8.0 
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: web_dev_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: